### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "password123"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "customer@example.com",
  "password": "customer123"
}

### Protected route
GET http://localhost:5000/api/protected
Authorization: Bearer TOKEN

### Get all products
GET http://localhost:5000/api/products

### Get one product
GET http://localhost:5000/api/products/6ab9835c0d6854bef0c03de3

### Create a product
POST http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer TOKEN

{
  "name": "Smart Watch",
  "description": "Modern smart watch with fitness tracking",
  "price": 129.99,
  "image": "https://example.com/watch.jpg",
  "category": "Electronics",
  "stock": 8
}

### Update a product as admin
PUT http://localhost:5000/api/products/6ab988f3020ed098b4bd54f2
Content-Type: application/json
Authorization: Bearer TOKEN

{
  "price": 39.99
}

### Delete a product as admin
DELETE http://localhost:5000/api/products/6ab988f3020ed098b4bd54f2
Authorization: Bearer TOKEN

### Create Order
POST http://localhost:5000/api/orders
Content-Type: application/json
Authorization: Bearer TOKEN

{
  "items": [
    {
      "product": "6ab9835c0d6854bef0c03de3",
      "name": "Wireless Headphones",
      "price": 79.99,
      "quantity": 2
    }
  ],
  "totalPrice": 159.98
}

### Get My Orders
GET http://localhost:5000/api/orders/my-orders
Authorization: Bearer TOKEN